language: generic

services:
- docker

script:
- cd scripts/
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_LOGIN" --password-stdin
- "./build_docker_images.sh prod"

notifications:
  email:
    on_success: never
    on_failure: always

after_success:
- bash <(curl -s https://codecov.io/bash)

