version: "3.7"

services:
  compressor:
    image: animal505/compressor:latest
    environment:
      REDIS_HOST: "redis"
      EMAIL: "${EMAIL}"
      PASSWORD: "${PASSWORD}"
      PCLOUD_LOGIN: "${PCLOUD_LOGIN}"
      PCLOUD_PASSWORD: "${PCLOUD_PASSWORD}"

  inputhandler:
    image: animal505/inputhandler:latest
    ports:
      - 8085:8080
    environment:
      REDIS_HOST: "redis"
      SERVER_PORT: 8080

  redis:
    image: redis
