version: "3.7"

services:
  compressor:
    image: animal505/compressor:latest
    container_name: compressor
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"
      EMAIL: "${EMAIL}"
      PASSWORD: "${PASSWORD}"
      PCLOUD_LOGIN: "${PCLOUD_LOGIN}"
      PCLOUD_PASSWORD: "${PCLOUD_PASSWORD}"

  inputhandler:
    image: animal505/inputhandler:latest
    container_name: inputhandler
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"
      SERVER_PORT: 8080

  frontend:
    image: animal505/frontend:latest
    container_name: frontend
    restart: always
    environment:
      API_HOST: "inputhandler"
      SERVER_PORT: 8080    

  reverseproxy:
    image: animal505/reverseproxy:latest
    container_name: reverseproxy
    restart: always
    ports:
      - 8080:8080

  redis:
    container_name: redis
    image: redis
